# -*- coding: utf-8 -*-
"""Random password generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaPI0_NEXzWrLo7t7LUBYwENc2rpAX8L
"""

import random
import string


print("     RANDOM PASSWORD GENERATOR")
print("======================================")

while True:
    try:
        length = int(input("\nEnter password length (minimum 8): "))

        if length < 8:
            print("Error: Password length must be at least 8.")
            continue

        print("\nChoose character types:")
        print("1. Uppercase letters")
        print("2. Lowercase letters")
        print("3. Numbers")
        print("4. Symbols")

        choices = input(
            "Enter your choices separated by spaces (example: 1 2 3 4): "
        ).split()

        valid_choices = {"1", "2", "3", "4"}
        selected_choices = set(choices) & valid_choices

        if len(selected_choices) < 2:
            print("Error: Select at least 2 valid character types.")
            continue

        character_sets = []

        if "1" in selected_choices:
            character_sets.append(string.ascii_uppercase)

        if "2" in selected_choices:
            character_sets.append(string.ascii_lowercase)

        if "3" in selected_choices:
            character_sets.append(string.digits)

        if "4" in selected_choices:
            character_sets.append(string.punctuation)

        all_characters = "".join(character_sets)

        password = "".join(
            random.choice(all_characters)
            for _ in range(length)
        )

        print("\nGenerated Password:", password)

        again = input(
            "\nGenerate another password? (yes/no): "
        ).lower()

        if again != "yes":
            print("Thank you for using the Password Generator!")
            break

    except ValueError:
        print("Error: Please enter a valid number.")